[build]
  publish = "out"
  command = "rm -rf out && mkdir out && rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='.gitignore' --exclude='.netlify' ./ out/ || true"

[context.production.environment]
  NODE_ENV = "production"
